# Generated by Django 5.1 on 2024-08-31 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('use_for', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('item_weight', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos')),
                ('available', models.CharField(choices=[('in-stock', 'in-stock'), ('out-of-stock', 'out-of-stock')], max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand_table')),
            ],
        ),
    ]
