# Generated by Django 5.1 on 2024-08-31 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_comment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_table',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product_table'),
        ),
        migrations.AlterField(
            model_name='comment_table',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='comment_table',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment_table',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment_table',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
