# Generated by Django 5.1 on 2024-08-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_comment_table_product_alter_comment_table_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_table',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
