# Generated by Django 5.0 on 2024-09-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_code',
            name='available',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=100, null=True),
        ),
    ]
