# Generated by Django 5.0 on 2024-09-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_coupon_code_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon_code',
            name='available',
        ),
        migrations.RemoveField(
            model_name='coupon_code',
            name='user',
        ),
        migrations.AddField(
            model_name='coupon_code',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon_code',
            name='active_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coupon_code',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon_code',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
