# Generated by Django 5.0 on 2024-09-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_coupon_code_available_remove_coupon_code_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon_code',
        ),
    ]
