# Generated by Django 5.0 on 2024-09-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='COUPON_CODER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
                ('discount_amount', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('active_date', models.DateField(null=True)),
                ('expire_date', models.DateField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
