# Generated by Django 5.0 on 2024-09-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_coupon_coder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COUPON_CODER',
        ),
    ]
