# Generated by Django 5.1 on 2024-09-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_coupon_coder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
                ('discount', models.PositiveIntegerField(null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('expire_date', models.DateField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
