# Generated by Django 5.1 on 2024-09-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_discount_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount_table',
            old_name='status',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='discount_table',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='discount_table',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='discount_table',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='discount_table',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='discount_table',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='discount_table',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
