# Generated by Django 5.1 on 2024-09-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_status_discount_table_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount_table',
        ),
    ]
