# Generated by Django 5.1 on 2024-09-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_delete_discount_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True)),
                ('discount', models.PositiveIntegerField(null=True)),
                ('expire_date', models.DateField(null=True)),
            ],
        ),
    ]
