# Generated by Django 5.1 on 2024-09-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='coupon_used',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
