# Generated by Django 5.1 on 2024-09-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_cart_item_coupon_code_cart_item_coupon_used_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='C',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='coupon_used',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='total_price',
        ),
    ]
