# Generated by Django 5.1 on 2024-09-02 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_checkout_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout_table',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cart_item'),
        ),
    ]
