# Generated by Django 5.1 on 2024-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_rating_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True)),
                ('discount', models.PositiveIntegerField(null=True)),
                ('active', models.BooleanField(null=True)),
            ],
        ),
    ]
