# Generated by Django 5.1 on 2024-09-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_cou'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cou',
        ),
    ]
