# Generated by Django 5.1 on 2024-09-12 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.register_table'),
        ),
    ]
