# Generated by Django 5.1 on 2024-09-12 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_coupon_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
    ]
